### ISSUE TITLE
Fix issues with gitlab.com

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-operator#83]
Managing git repos on gitlab.com used to work, but now fails with the following error:

```
{"level":"error","ts":1594726227.2132478,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"gitrepo-controller","request":"lieutenant/c-divine-dew-5824","error":"status code was 503","...}
```

As this breaks the [getting started guide](https://syn.tools/syn/getting-started.html) we should investigate and eventually fix the issue.

**Comment by Kidswiss** [comment]
The issue is with the git implementation detection and CloudFlare.

To detect if it's a gitlab instance the operator won't query the API as every API call already requires valid credentials. So it checks if the gitlab login page exists.

That's where CloudFlare's browser detection comes in. It detects that the operator is not a browser and throws the 503.  It can easily be reproduced via `curl`:

```
➜ curl https://gitlab.com/users/sign_in -I
HTTP/2 503
date: Wed, 22 Jul 2020 11:29:48 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
set-cookie: __cfduid=d658dd27d35c485195fb96ca79a9329ae1595417388; expires=Fri, 21-Aug-20 11:29:48 GMT; path=/; domain=.gitlab.com; HttpOnly; SameSite=Lax; Secure
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
cf-request-id: 0417e27e6c0000cc4ae424b200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5b6cd3771aeecc4a-ZRH
```
